version: '3'

services:

#   test-fastapi-keycloak:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     restart: always
#     depends_on:
#       - keycloak
#       # keycloak:
#       #   condition: service_healthy
#     network_mode: host

  keycloak:
    image: jboss/keycloak:15.0.2
    volumes:
      - ./my-realm-export.json:/tmp/my-realm-export.json
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=keycloak-postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_SCHEMA=public
      - DB_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/my-realm-export.json
    ports:
      - 8080:8080
    depends_on:
      - keycloak-postgres
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://keycloak:8080"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 2

  keycloak-postgres:
    image: postgres:13.4-alpine3.14
    volumes:
      - ./data/keycloak-postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=keycloak
