version: "3"

dotenv: [".env"]

tasks:
  test:
    cmds:
      - poetry run pytest
        # --cov=fastapi_oidc \
        # --cov-report=term-missing
        # --cov-report=xml tests ${@}
    silent: true
  build:
    cmds:
      - poetry build
    sources:
      - fastapi_oidc/**
      - poetry.lock
      - pyproject.toml
    generates:
      - dist/**
  publish:
    deps: [build]
    cmds:
      - echo "Publishing as $PYPI_USERNAME"
      - poetry publish -u $PYPI_USERNAME -p $PYPI_PASSWORD
    # sources:
    #   # TODO This is erroneously registering as up to date
    #   # After a build has been run :( )
    #   - dist/**
    #   - poetry.lock
    #   - pyproject.toml
    # status:
    #   - echo "Return nonzero code if we shouldn't publish"
  clean:
    cmds:
      - rm -rf ./build ./dist ./*.egg-info __pycache__
  build_docs:
    cmds:
      - echo "Not implemented"
